# action.yml
name: 'Jajal Docker Action'
description: 'Jajal docker action'

author: Muhammad Rendra

branding:
  icon: at-sign
  color: purple

inputs:
  token:  # id of input
    description: 'GitHub token'
    default: ${{ github.token }}
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    # CI: true
    # GITHUB_ACTIONS: true
