on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    permissions:
      contents: write
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      # Import GPG
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        with:
          git_user_signingkey: true
          git_committer_name: ${{ vars.GIT_COMMITTER_NAME }}
          git_committer_email: ${{ vars.GIT_COMMITTER_EMAIL }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      
      #
      - name: Check Node Pre
        run: ls -laihs && node --version || true

      # Hello world action step
      - name: Hello world action step
        uses: mnrendra/jajal-docker-action@9f83055b8d732dd0a917f32a2279728cf1de35b2

      #
      - name: Check Node Post
        run: ls -laihs && node --version || true
